const $=s=>document.querySelector(s),api='/api';let projects=[],editing=null,editingClient=null;
const note=t=>$('#notice').textContent=t;
async function req(u,o={}){const r=await fetch(u,o),d=await r.json();if(!r.ok)throw Error(d.error||'No fue posible guardar el cambio');return d}
async function validateImage(file,min={width:1600,height:1200,label:'proyecto'}){if(!file)return;if(file.size>10*1024*1024)throw Error('La imagen supera 10 MB. Reduce su peso antes de subirla.');const url=URL.createObjectURL(file);try{const image=new Image();await new Promise((ok,bad)=>{image.onload=ok;image.onerror=bad;image.src=url});if(image.naturalWidth<min.width||image.naturalHeight<min.height){if(min.recommended)return;throw Error(`La imagen de ${min.label} debe ser de al menos ${min.width} × ${min.height} px. La seleccionada mide ${image.naturalWidth} × ${image.naturalHeight} px.`)}}finally{URL.revokeObjectURL(url)}}
async function upload(file,min){if(!file||!file.name||file.size===0)return '';await validateImage(file,min);const form=new FormData();form.append('image',file);return(await req(api+'/upload',{method:'POST',body:form})).url}
const phases=$('#phases');
function addPhase(x={}){const p=document.createElement('div');p.dataset.image=x.image||'';p.innerHTML=`<label>Titulo de fase<input class="pt" placeholder="Ej. Cimentacion" value="${x.title||''}"></label><label>Descripcion de fase<textarea class="pd" placeholder="Que se ejecuto en esta etapa?">${x.description||''}</textarea></label><label>Imagen de fase<input class="pi" type="file" accept="image/jpeg,image/png,image/webp"><small>${x.image?'Imagen actual conservada. Puedes sustituirla con otra de 1600 × 1200 px minimo.':'Recomendado: 1600 × 1200 px minimo · JPG, PNG o WEBP.'}</small></label><button type="button">Eliminar fase</button>`;p.querySelector('button').onclick=()=>p.remove();phases.append(p)}
$('#phase').onclick=()=>addPhase();
function toggle(){const is=$('#format').value==='phases';$('#ba').hidden=is;phases.hidden=!is;if(is&&!phases.children.length)addPhase()}$('#format').onchange=toggle;
function resetProject(){editing=null;$('#project').reset();phases.innerHTML='';$('#ba').hidden=false;delete $('#ba').dataset.before;delete $('#ba').dataset.after;$('#project .button-primary').textContent='Guardar proyecto'}
function edit(id){const x=projects.find(p=>p.id===id);if(!x)return;editing=x;const f=$('#project');f.title.value=x.title;f.category.value=x.category;f.location.value=x.location||'';f.description.value=x.description;f.format.value=x.format;phases.innerHTML='';if(x.format==='phases')(x.phases||[]).forEach(addPhase);else{f.baDescription.value=x.beforeAfter?.description||'';$('#ba').dataset.before=x.beforeAfter?.before||'';$('#ba').dataset.after=x.beforeAfter?.after||''}toggle();f.querySelector('.button-primary').textContent='Guardar cambios';f.scrollIntoView({behavior:'smooth',block:'start'});note('Editando: '+x.title)}window.edit=edit;
$('#project').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),category=f.get('category'),x={title:f.get('title'),category,type:{turismo:'Turismo',tratamiento:'Plantas de tratamiento',remodelacion:'Remodelacion'}[category],location:f.get('location'),description:f.get('description'),format:f.get('format')};try{if(x.format==='beforeAfter'){const b=$('#ba');x.beforeAfter={before:await upload(f.get('before'))||b.dataset.before||'',after:await upload(f.get('after'))||b.dataset.after||'',description:f.get('baDescription')};if(!x.beforeAfter.before||!x.beforeAfter.after)throw Error('Selecciona una imagen de antes y otra de despues.');x.coverImage=x.beforeAfter.after}else{x.phases=[];for(const p of phases.children){const title=p.querySelector('.pt').value,description=p.querySelector('.pd').value;if(!title||!description)throw Error('Completa el titulo y la descripcion de cada fase.');const image=await upload(p.querySelector('.pi').files[0])||p.dataset.image;if(!image)throw Error('Cada fase necesita una imagen.');x.phases.push({title,description,image})}x.coverImage=x.phases[0]?.image||''}await req(editing?`${api}/projects/${editing.id}`:`${api}/projects`,{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(x)});note(editing?'Cambios del proyecto guardados.':'Proyecto publicado correctamente.');resetProject();load()}catch(err){note(err.message)}};
function resetClient(){editingClient=null;$('#client').reset();$('#client .button-primary').textContent='Subir logo'}
function editClient(id){const x=(window.arquimaseClients||[]).find(c=>c.id===id);if(!x)return;editingClient=x;$('#client').name.value=x.name;$('#client .button-primary').textContent='Guardar cambios';$('#client').scrollIntoView({behavior:'smooth',block:'center'});note('Editando logo: '+x.name+'. Sube otro archivo solo si deseas reemplazarlo.')}window.editClient=editClient;
$('#client').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{const logo=await upload(f.get('logo'),{width:800,height:400,label:'logo',recommended:true})||(editingClient?.logo||'');if(!logo)throw Error('Selecciona un logo para publicar.');await req(editingClient?`${api}/clients/${editingClient.id}`:`${api}/clients`,{method:editingClient?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:f.get('name'),logo})});note(editingClient?'Logo actualizado correctamente.':'Logo publicado correctamente.');resetClient();load()}catch(err){note(err.message)}};
async function del(t,id){if(confirm('Eliminar este elemento?'))try{await req(`${api}/${t}/${id}`,{method:'DELETE'});note('Elemento eliminado.');load()}catch(err){note(err.message)}}window.del=del;
async function moveProject(id,direction){const index=projects.findIndex(project=>project.id===id),target=index+direction;if(index<0||target<0||target>=projects.length)return;const ordered=[...projects];[ordered[index],ordered[target]]=[ordered[target],ordered[index]];try{await req(`${api}/projects/reorder`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids:ordered.map(project=>project.id)})});note('Orden de proyectos actualizado.');load()}catch(err){note(err.message)}}window.moveProject=moveProject;
function render(d){projects=d.projects||[];window.arquimaseClients=d.clients||[];$('#projects').innerHTML=projects.map((x,index)=>`<div class="item"><img src="${x.coverImage||''}" alt=""><span><b>${x.title}</b><br>${x.type}</span><div class="order-controls"><button onclick="moveProject('${x.id}',-1)" ${index===0?'disabled':''} aria-label="Subir proyecto">↑</button><button onclick="moveProject('${x.id}',1)" ${index===projects.length-1?'disabled':''} aria-label="Bajar proyecto">↓</button></div><button class="edit" onclick="edit('${x.id}')">Editar</button><button onclick="del('projects','${x.id}')">Eliminar</button></div>`).join('')||'Aun no hay proyectos publicados.';$('#clients').innerHTML=window.arquimaseClients.map(x=>`<div class="item"><img src="${x.logo}" alt="${x.name}"><span><b>${x.name}</b><br><small>Logo publicado</small></span><button class="edit" onclick="editClient('${x.id}')">Editar</button><button onclick="del('clients','${x.id}')">Eliminar</button></div>`).join('')||'Aun no hay logos publicados.';const labels={hero:'Portada principal',especialidades:'Especialidades',portafolio:'Portafolio',clientes:'Clientes',contacto:'Contacto'};$('#blocks').innerHTML=Object.entries(labels).map(([slot,label])=>{const image=d.siteImages?.[slot]||'';return `<div class="block"><div class="block-preview" style="background-image:${image?`url('${image}')`:'none'}"></div><div><b>${label}</b><small>${image?'Imagen actual cargada. Selecciona otra para sustituirla.':'Sin imagen personalizada.'} Recomendado: 1920 × 1080 px minimo.</small><input type="file" accept="image/jpeg,image/png,image/webp" data-slot="${slot}"></div><button class="button-primary" data-save="${slot}">Guardar imagen</button></div>`}).join('');document.querySelectorAll('[data-save]').forEach(b=>b.onclick=async()=>{try{const slot=b.dataset.save,file=document.querySelector(`[data-slot="${slot}"]`).files[0];if(!file)throw Error('Selecciona una imagen para este bloque.');const url=await upload(file,{width:1920,height:1080,label:'fondo'});await req(`${api}/site-images/${slot}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({url})});note('Imagen de bloque guardada y lista para el sitio.');load()}catch(err){note(err.message)}})}
async function load(){try{render(await req(api+'/content'))}catch(err){note(err.message)}}load();
