const $=s=>document.querySelector(s),api='/api';let projects=[],editing=null;
const note=t=>$('#notice').textContent=t;async function req(u,o={}){let r=await fetch(u,o),d=await r.json();if(!r.ok)throw Error(d.error);return d}async function upload(f){if(!f)return '';let d=new FormData();d.append('image',f);return(await req(api+'/upload',{method:'POST',body:d})).url}
const phases=$('#phases');function addPhase(x={}){let p=document.createElement('div');p.dataset.image=x.image||'';p.innerHTML=`<input class="pt" placeholder="Título de fase" value="${x.title||''}"><textarea class="pd" placeholder="Descripción de fase">${x.description||''}</textarea><input class="pi" type="file" accept="image/*"><small>${x.image?'Imagen actual conservada':'Selecciona una imagen'}</small><button type="button">Eliminar</button>`;p.querySelector('button').onclick=()=>p.remove();phases.append(p)}$('#phase').onclick=()=>addPhase();
function toggle(){let is=$('#format').value==='phases';$('#ba').hidden=is;phases.hidden=!is;if(is&&!phases.children.length)addPhase()}$('#format').onchange=toggle;
function reset(){editing=null;$('#project').reset();phases.innerHTML='';$('#ba').hidden=false;$('#project button[type=submit]').textContent='Guardar proyecto'}
function edit(id){let x=projects.find(p=>p.id===id);if(!x)return;editing=x;let f=$('#project');f.title.value=x.title;f.category.value=x.category;f.location.value=x.location||'';f.description.value=x.description;f.format.value=x.format;phases.innerHTML='';if(x.format==='phases')(x.phases||[]).forEach(addPhase);else{f.baDescription.value=x.beforeAfter?.description||'';$('#ba').dataset.before=x.beforeAfter?.before||'';$('#ba').dataset.after=x.beforeAfter?.after||''}toggle();f.querySelector('button[type=submit]').textContent='Guardar cambios';f.scrollIntoView({behavior:'smooth'});note('Editando: '+x.title)}window.edit=edit;
$('#project').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),cat=f.get('category'),x={title:f.get('title'),category:cat,type:{turismo:'Turismo',tratamiento:'Plantas de tratamiento',remodelacion:'Remodelación'}[cat],location:f.get('location'),description:f.get('description'),format:f.get('format')};try{if(x.format==='beforeAfter'){let b=$('#ba');x.beforeAfter={before:await upload(f.get('before'))||b.dataset.before||'',after:await upload(f.get('after'))||b.dataset.after||'',description:f.get('baDescription')};x.coverImage=x.beforeAfter.after||x.beforeAfter.before}else{x.phases=[];for(let p of phases.children){let title=p.querySelector('.pt').value,description=p.querySelector('.pd').value;if(!title||!description)throw Error('Completa cada fase');x.phases.push({title,description,image:await upload(p.querySelector('.pi').files[0])||p.dataset.image})}x.coverImage=x.phases[0]?.image||''}await req(editing?`${api}/projects/${editing.id}`:`${api}/projects`,{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(x)});note(editing?'Cambios guardados':'Proyecto publicado');reset();load()}catch(err){note(err.message)}};
$('#client').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target);try{await req(api+'/clients',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:f.get('name'),logo:await upload(f.get('logo'))})});e.target.reset();note('Logo publicado');load()}catch(err){note(err.message)}};
async function del(t,id){if(confirm('¿Eliminar?')){await req(`${api}/${t}/${id}`,{method:'DELETE'});load()}}window.del=del;
function render(d){projects=d.projects;$('#projects').innerHTML=projects.map(x=>`<div class="item"><img src="${x.coverImage||''}"><span><b>${x.title}</b><br>${x.type}</span><button class="edit" onclick="edit('${x.id}')">Editar</button><button onclick="del('projects','${x.id}')">Eliminar</button></div>`).join('')||'Sin proyectos';$('#clients').innerHTML=d.clients.map(x=>`<div class="item"><img src="${x.logo}"><b>${x.name}</b><button onclick="del('clients','${x.id}')">Eliminar</button></div>`).join('')||'Sin logos';$('#blocks').innerHTML=['hero','especialidades','portafolio','clientes','contacto'].map(s=>`<div class="block"><b>${s}</b><input type="file" accept="image/*" data-slot="${s}"><button data-save="${s}">Guardar imagen</button></div>`).join('');document.querySelectorAll('[data-save]').forEach(b=>b.onclick=async()=>{try{let slot=b.dataset.save,file=document.querySelector(`[data-slot=${slot}]`).files[0];if(!file)throw Error('Selecciona una imagen');await req(`${api}/site-images/${slot}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:await upload(file)})});note('Imagen guardada')}catch(e){note(e.message)}})}async function load(){try{render(await req(api+'/content'))}catch(e){note(e.message)}}load();
