// Backend Arquimase + Supabase. Ejecuta: node server.js
const http = require('http'); const fs = require('fs'); const path = require('path'); const crypto = require('crypto');
const root = __dirname;
const env = Object.fromEntries(fs.readFileSync(path.join(root, '.env'), 'utf8').split(/\r?\n/).filter(Boolean).map(line => { const i = line.indexOf('='); return [line.slice(0,i),line.slice(i+1)]; }));
const base = env.SUPABASE_URL; const key = env.SUPABASE_SERVICE_ROLE_KEY; const bucket = env.SUPABASE_STORAGE_BUCKET || 'arquimase-media';
if (!base || !key) throw new Error('Faltan credenciales de Supabase en .env');
const headers = { apikey:key, Authorization:`Bearer ${key}` };
const json = (res,status,data) => { res.writeHead(status,{'Content-Type':'application/json; charset=utf-8'}); res.end(JSON.stringify(data)); };
const readBody = req => new Promise((resolve,reject)=>{let parts=[],size=0;req.on('data',part=>{size+=part.length;if(size>12*1024*1024){reject(Error('Máximo 10 MB'));req.destroy()}else parts.push(part)});req.on('end',()=>resolve(Buffer.concat(parts)));req.on('error',reject)});
async function sb(route, options={}) { const r=await fetch(`${base}/rest/v1/${route}`,{...options,headers:{...headers,...options.headers}}); if(!r.ok) throw Error(await r.text()); return r.status===204?null:r.json(); }
function parseMultipart(buffer,boundary){let result=[],mark=Buffer.from('--'+boundary),at=buffer.indexOf(mark);while(at>=0){let next=buffer.indexOf(mark,at+mark.length);if(next<0)break;let p=buffer.slice(at+mark.length+2,next-2),split=p.indexOf(Buffer.from('\r\n\r\n'));if(split>0){let h=p.slice(0,split).toString(),name=/name="([^"]+)"/.exec(h)?.[1],filename=/filename="([^"]+)"/.exec(h)?.[1],type=/Content-Type:\s*([^\r\n]+)/i.exec(h)?.[1];if(name)result.push({name,filename,type,content:p.slice(split+4)})}at=next}return result;}
async function upload(req,res){const boundary=/boundary=(.+)/.exec(req.headers['content-type']||'')?.[1];const file=parseMultipart(await readBody(req),boundary).find(x=>x.name==='image'&&x.filename);if(!file)throw Error('Selecciona una imagen');const ext=path.extname(file.filename).toLowerCase();if(!['.jpg','.jpeg','.png','.webp'].includes(ext))throw Error('Usa JPG, PNG o WEBP');const name=`${Date.now()}-${crypto.randomUUID()}${ext}`;const r=await fetch(`${base}/storage/v1/object/${bucket}/${name}`,{method:'POST',headers:{...headers,'Content-Type':file.type||'application/octet-stream'},body:file.content});if(!r.ok)throw Error(await r.text());const signed=await fetch(`${base}/storage/v1/object/sign/${bucket}/${name}`,{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({expiresIn:31536000})});if(!signed.ok)throw Error(await signed.text());const data=await signed.json();json(res,201,{url:`${base}/storage/v1${data.signedURL}`});}
function staticFile(res,pathname){let file=path.join(root,pathname==='/'?'index.html':pathname.replace(/^\//,''));if(!file.startsWith(root)||!fs.existsSync(file)||fs.statSync(file).isDirectory())return json(res,404,{error:'No encontrado'});let ext=path.extname(file),types={'.html':'text/html','.css':'text/css','.js':'application/javascript','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream'});fs.createReadStream(file).pipe(res);}
http.createServer(async(req,res)=>{const url=new URL(req.url,'http://localhost'),p=decodeURIComponent(url.pathname);try{if(req.method==='GET'&&p==='/api/content'){const [projects,clients,images]=await Promise.all([sb('arquimase_projects?select=*&order=created_at.desc'),sb('arquimase_clients?select=*&order=created_at.desc'),sb('arquimase_site_images?select=*')]);return json(res,200,{projects:projects.map(x=>({...x,coverImage:x.cover_image,beforeAfter:x.before_after})),clients,siteImages:Object.fromEntries(images.map(x=>[x.slot,x.url]))});}if(req.method==='POST'&&p==='/api/upload')return upload(req,res);if((req.method==='POST'&&p==='/api/projects')||(req.method==='PUT'&&p.startsWith('/api/projects/'))){const x=JSON.parse((await readBody(req)).toString()),record={title:x.title,category:x.category,type:x.type,location:x.location,description:x.description,format:x.format,cover_image:x.coverImage,before_after:x.beforeAfter,phases:x.phases};const isEdit=req.method==='PUT';const route=isEdit?`arquimase_projects?id=eq.${p.split('/').pop()}`:'arquimase_projects';const [item]=await sb(route,{method:isEdit?'PATCH':'POST',headers:{'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify(record)});return json(res,isEdit?200:201,item);}if(req.method==='DELETE'&&p.startsWith('/api/projects/')){await sb(`arquimase_projects?id=eq.${p.split('/').pop()}`,{method:'DELETE'});return json(res,200,{ok:true});}if(req.method==='POST'&&p==='/api/clients'){const x=JSON.parse((await readBody(req)).toString());const [item]=await sb('arquimase_clients',{method:'POST',headers:{'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify(x)});return json(res,201,item);}if(req.method==='DELETE'&&p.startsWith('/api/clients/')){await sb(`arquimase_clients?id=eq.${p.split('/').pop()}`,{method:'DELETE'});return json(res,200,{ok:true});}if(req.method==='PUT'&&p.startsWith('/api/site-images/')){const slot=p.split('/').pop(),x=JSON.parse((await readBody(req)).toString());await sb('arquimase_site_images',{method:'POST',headers:{'Content-Type':'application/json',Prefer:'resolution=merge-duplicates'},body:JSON.stringify({slot,url:x.url})});return json(res,200,x);}return staticFile(res,p);}catch(error){json(res,400,{error:error.message});}}).listen(3000,()=>console.log('Arquimase conectado a Supabase: http://localhost:3000/admin.html'));
